from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GameUpdate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, participants=None):  # noqa: E501
        """GameUpdate - a model defined in OpenAPI

        :param participants: The participants of this GameUpdate.  # noqa: E501
        :type participants: int
        """
        self.openapi_types = {
            'participants': int
        }

        self.attribute_map = {
            'participants': 'participants'
        }

        self._participants = participants

    @classmethod
    def from_dict(cls, dikt) -> 'GameUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GameUpdate of this GameUpdate.  # noqa: E501
        :rtype: GameUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def participants(self) -> int:
        """Gets the participants of this GameUpdate.


        :return: The participants of this GameUpdate.
        :rtype: int
        """
        return self._participants

    @participants.setter
    def participants(self, participants: int):
        """Sets the participants of this GameUpdate.


        :param participants: The participants of this GameUpdate.
        :type participants: int
        """
        if participants is None:
            raise ValueError("Invalid value for `participants`, must not be `None`")  # noqa: E501

        self._participants = participants
