from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class User(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, uid=None, name=None):  # noqa: E501
        """User - a model defined in OpenAPI

        :param uid: The uid of this User.  # noqa: E501
        :type uid: str
        :param name: The name of this User.  # noqa: E501
        :type name: str
        """
        self.openapi_types = {
            'uid': str,
            'name': str
        }

        self.attribute_map = {
            'uid': 'UID',
            'name': 'name'
        }

        self._uid = uid
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'User':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User of this User.  # noqa: E501
        :rtype: User
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uid(self) -> str:
        """Gets the uid of this User.


        :return: The uid of this User.
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid: str):
        """Sets the uid of this User.


        :param uid: The uid of this User.
        :type uid: str
        """

        self._uid = uid

    @property
    def name(self) -> str:
        """Gets the name of this User.


        :return: The name of this User.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this User.


        :param name: The name of this User.
        :type name: str
        """

        self._name = name
