from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class AddPlayerRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, uid=None, name=None):  # noqa: E501
        """AddPlayerRequest - a model defined in OpenAPI

        :param uid: The uid of this AddPlayerRequest.  # noqa: E501
        :type uid: str
        :param name: The name of this AddPlayerRequest.  # noqa: E501
        :type name: str
        """
        self.openapi_types = {
            'uid': str,
            'name': str
        }

        self.attribute_map = {
            'uid': 'uid',
            'name': 'name'
        }

        self._uid = uid
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'AddPlayerRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AddPlayerRequest of this AddPlayerRequest.  # noqa: E501
        :rtype: AddPlayerRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uid(self) -> str:
        """Gets the uid of this AddPlayerRequest.


        :return: The uid of this AddPlayerRequest.
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid: str):
        """Sets the uid of this AddPlayerRequest.


        :param uid: The uid of this AddPlayerRequest.
        :type uid: str
        """
        if uid is None:
            raise ValueError("Invalid value for `uid`, must not be `None`")  # noqa: E501

        self._uid = uid

    @property
    def name(self) -> str:
        """Gets the name of this AddPlayerRequest.


        :return: The name of this AddPlayerRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this AddPlayerRequest.


        :param name: The name of this AddPlayerRequest.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name
