from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class CardsCidTypeGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cardtype=None):  # noqa: E501
        """CardsCidTypeGet200Response - a model defined in OpenAPI

        :param cardtype: The cardtype of this CardsCidTypeGet200Response.  # noqa: E501
        :type cardtype: str
        """
        self.openapi_types = {
            'cardtype': str
        }

        self.attribute_map = {
            'cardtype': 'cardtype'
        }

        self._cardtype = cardtype

    @classmethod
    def from_dict(cls, dikt) -> 'CardsCidTypeGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The cards_cid_type_get_200_response of this CardsCidTypeGet200Response.  # noqa: E501
        :rtype: CardsCidTypeGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cardtype(self) -> str:
        """Gets the cardtype of this CardsCidTypeGet200Response.


        :return: The cardtype of this CardsCidTypeGet200Response.
        :rtype: str
        """
        return self._cardtype

    @cardtype.setter
    def cardtype(self, cardtype: str):
        """Sets the cardtype of this CardsCidTypeGet200Response.


        :param cardtype: The cardtype of this CardsCidTypeGet200Response.
        :type cardtype: str
        """

        self._cardtype = cardtype
