from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class CardInGames(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cid=None, uid=None, gid=None):  # noqa: E501
        """CardInGames - a model defined in OpenAPI

        :param cid: The cid of this CardInGames.  # noqa: E501
        :type cid: str
        :param uid: The uid of this CardInGames.  # noqa: E501
        :type uid: str
        :param gid: The gid of this CardInGames.  # noqa: E501
        :type gid: str
        """
        self.openapi_types = {
            'cid': str,
            'uid': str,
            'gid': str
        }

        self.attribute_map = {
            'cid': 'CID',
            'uid': 'UID',
            'gid': 'GID'
        }

        self._cid = cid
        self._uid = uid
        self._gid = gid

    @classmethod
    def from_dict(cls, dikt) -> 'CardInGames':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CardInGames of this CardInGames.  # noqa: E501
        :rtype: CardInGames
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cid(self) -> str:
        """Gets the cid of this CardInGames.


        :return: The cid of this CardInGames.
        :rtype: str
        """
        return self._cid

    @cid.setter
    def cid(self, cid: str):
        """Sets the cid of this CardInGames.


        :param cid: The cid of this CardInGames.
        :type cid: str
        """
        if cid is None:
            raise ValueError("Invalid value for `cid`, must not be `None`")  # noqa: E501

        self._cid = cid

    @property
    def uid(self) -> str:
        """Gets the uid of this CardInGames.


        :return: The uid of this CardInGames.
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid: str):
        """Sets the uid of this CardInGames.


        :param uid: The uid of this CardInGames.
        :type uid: str
        """
        if uid is None:
            raise ValueError("Invalid value for `uid`, must not be `None`")  # noqa: E501

        self._uid = uid

    @property
    def gid(self) -> str:
        """Gets the gid of this CardInGames.


        :return: The gid of this CardInGames.
        :rtype: str
        """
        return self._gid

    @gid.setter
    def gid(self, gid: str):
        """Sets the gid of this CardInGames.


        :param gid: The gid of this CardInGames.
        :type gid: str
        """
        if gid is None:
            raise ValueError("Invalid value for `gid`, must not be `None`")  # noqa: E501

        self._gid = gid
