from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GamesGidUsersUidCardCountGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, count=None):  # noqa: E501
        """GamesGidUsersUidCardCountGet200Response - a model defined in OpenAPI

        :param count: The count of this GamesGidUsersUidCardCountGet200Response.  # noqa: E501
        :type count: int
        """
        self.openapi_types = {
            'count': int
        }

        self.attribute_map = {
            'count': 'count'
        }

        self._count = count

    @classmethod
    def from_dict(cls, dikt) -> 'GamesGidUsersUidCardCountGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The games_gid_users_uid_card_count_get_200_response of this GamesGidUsersUidCardCountGet200Response.  # noqa: E501
        :rtype: GamesGidUsersUidCardCountGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def count(self) -> int:
        """Gets the count of this GamesGidUsersUidCardCountGet200Response.


        :return: The count of this GamesGidUsersUidCardCountGet200Response.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count: int):
        """Sets the count of this GamesGidUsersUidCardCountGet200Response.


        :param count: The count of this GamesGidUsersUidCardCountGet200Response.
        :type count: int
        """

        self._count = count
