from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GamesGidNextPlayerUidGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, uid=None):  # noqa: E501
        """GamesGidNextPlayerUidGet200Response - a model defined in OpenAPI

        :param uid: The uid of this GamesGidNextPlayerUidGet200Response.  # noqa: E501
        :type uid: str
        """
        self.openapi_types = {
            'uid': str
        }

        self.attribute_map = {
            'uid': 'uid'
        }

        self._uid = uid

    @classmethod
    def from_dict(cls, dikt) -> 'GamesGidNextPlayerUidGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The games_gid_next_player_uid_get_200_response of this GamesGidNextPlayerUidGet200Response.  # noqa: E501
        :rtype: GamesGidNextPlayerUidGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uid(self) -> str:
        """Gets the uid of this GamesGidNextPlayerUidGet200Response.


        :return: The uid of this GamesGidNextPlayerUidGet200Response.
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid: str):
        """Sets the uid of this GamesGidNextPlayerUidGet200Response.


        :param uid: The uid of this GamesGidNextPlayerUidGet200Response.
        :type uid: str
        """

        self._uid = uid
