from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GamesPost201Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, gid=None):  # noqa: E501
        """GamesPost201Response - a model defined in OpenAPI

        :param gid: The gid of this GamesPost201Response.  # noqa: E501
        :type gid: str
        """
        self.openapi_types = {
            'gid': str
        }

        self.attribute_map = {
            'gid': 'gid'
        }

        self._gid = gid

    @classmethod
    def from_dict(cls, dikt) -> 'GamesPost201Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The games_post_201_response of this GamesPost201Response.  # noqa: E501
        :rtype: GamesPost201Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def gid(self) -> str:
        """Gets the gid of this GamesPost201Response.

        Die ID des neu erstellten Spiels.  # noqa: E501

        :return: The gid of this GamesPost201Response.
        :rtype: str
        """
        return self._gid

    @gid.setter
    def gid(self, gid: str):
        """Sets the gid of this GamesPost201Response.

        Die ID des neu erstellten Spiels.  # noqa: E501

        :param gid: The gid of this GamesPost201Response.
        :type gid: str
        """

        self._gid = gid
