from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GamesGidUsersUidPlayerNumberGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, playernumber=None):  # noqa: E501
        """GamesGidUsersUidPlayerNumberGet200Response - a model defined in OpenAPI

        :param playernumber: The playernumber of this GamesGidUsersUidPlayerNumberGet200Response.  # noqa: E501
        :type playernumber: int
        """
        self.openapi_types = {
            'playernumber': int
        }

        self.attribute_map = {
            'playernumber': 'playernumber'
        }

        self._playernumber = playernumber

    @classmethod
    def from_dict(cls, dikt) -> 'GamesGidUsersUidPlayerNumberGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The games_gid_users_uid_player_number_get_200_response of this GamesGidUsersUidPlayerNumberGet200Response.  # noqa: E501
        :rtype: GamesGidUsersUidPlayerNumberGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def playernumber(self) -> int:
        """Gets the playernumber of this GamesGidUsersUidPlayerNumberGet200Response.


        :return: The playernumber of this GamesGidUsersUidPlayerNumberGet200Response.
        :rtype: int
        """
        return self._playernumber

    @playernumber.setter
    def playernumber(self, playernumber: int):
        """Sets the playernumber of this GamesGidUsersUidPlayerNumberGet200Response.


        :param playernumber: The playernumber of this GamesGidUsersUidPlayerNumberGet200Response.
        :type playernumber: int
        """

        self._playernumber = playernumber
