from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GamesGidCurrentRoundIdGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, rid=None):  # noqa: E501
        """GamesGidCurrentRoundIdGet200Response - a model defined in OpenAPI

        :param rid: The rid of this GamesGidCurrentRoundIdGet200Response.  # noqa: E501
        :type rid: str
        """
        self.openapi_types = {
            'rid': str
        }

        self.attribute_map = {
            'rid': 'rid'
        }

        self._rid = rid

    @classmethod
    def from_dict(cls, dikt) -> 'GamesGidCurrentRoundIdGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The games_gid_current_round_id_get_200_response of this GamesGidCurrentRoundIdGet200Response.  # noqa: E501
        :rtype: GamesGidCurrentRoundIdGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def rid(self) -> str:
        """Gets the rid of this GamesGidCurrentRoundIdGet200Response.


        :return: The rid of this GamesGidCurrentRoundIdGet200Response.
        :rtype: str
        """
        return self._rid

    @rid.setter
    def rid(self, rid: str):
        """Sets the rid of this GamesGidCurrentRoundIdGet200Response.


        :param rid: The rid of this GamesGidCurrentRoundIdGet200Response.
        :type rid: str
        """

        self._rid = rid
