from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Jasskarte(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cid=None, symbol=None, cardtype=None, path=None):  # noqa: E501
        """Jasskarte - a model defined in OpenAPI

        :param cid: The cid of this Jasskarte.  # noqa: E501
        :type cid: str
        :param symbol: The symbol of this Jasskarte.  # noqa: E501
        :type symbol: str
        :param cardtype: The cardtype of this Jasskarte.  # noqa: E501
        :type cardtype: str
        :param path: The path of this Jasskarte.  # noqa: E501
        :type path: str
        """
        self.openapi_types = {
            'cid': str,
            'symbol': str,
            'cardtype': str,
            'path': str
        }

        self.attribute_map = {
            'cid': 'cid',
            'symbol': 'symbol',
            'cardtype': 'cardtype',
            'path': 'path'
        }

        self._cid = cid
        self._symbol = symbol
        self._cardtype = cardtype
        self._path = path

    @classmethod
    def from_dict(cls, dikt) -> 'Jasskarte':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Jasskarte of this Jasskarte.  # noqa: E501
        :rtype: Jasskarte
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cid(self) -> str:
        """Gets the cid of this Jasskarte.

        Eindeutige ID der Karte.  # noqa: E501

        :return: The cid of this Jasskarte.
        :rtype: str
        """
        return self._cid

    @cid.setter
    def cid(self, cid: str):
        """Sets the cid of this Jasskarte.

        Eindeutige ID der Karte.  # noqa: E501

        :param cid: The cid of this Jasskarte.
        :type cid: str
        """

        self._cid = cid

    @property
    def symbol(self) -> str:
        """Gets the symbol of this Jasskarte.

        Farbe/Symbol der Karte (z.B. Schella, Rose).  # noqa: E501

        :return: The symbol of this Jasskarte.
        :rtype: str
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol: str):
        """Sets the symbol of this Jasskarte.

        Farbe/Symbol der Karte (z.B. Schella, Rose).  # noqa: E501

        :param symbol: The symbol of this Jasskarte.
        :type symbol: str
        """

        self._symbol = symbol

    @property
    def cardtype(self) -> str:
        """Gets the cardtype of this Jasskarte.

        Typ der Karte (z.B. Ass, König, 6).  # noqa: E501

        :return: The cardtype of this Jasskarte.
        :rtype: str
        """
        return self._cardtype

    @cardtype.setter
    def cardtype(self, cardtype: str):
        """Sets the cardtype of this Jasskarte.

        Typ der Karte (z.B. Ass, König, 6).  # noqa: E501

        :param cardtype: The cardtype of this Jasskarte.
        :type cardtype: str
        """

        self._cardtype = cardtype

    @property
    def path(self) -> str:
        """Gets the path of this Jasskarte.

        Pfad zum Bild der Karte.  # noqa: E501

        :return: The path of this Jasskarte.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path: str):
        """Sets the path of this Jasskarte.

        Pfad zum Bild der Karte.  # noqa: E501

        :param path: The path of this Jasskarte.
        :type path: str
        """

        self._path = path
