from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class StartNewRoundRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, whichround=None):  # noqa: E501
        """StartNewRoundRequest - a model defined in OpenAPI

        :param whichround: The whichround of this StartNewRoundRequest.  # noqa: E501
        :type whichround: int
        """
        self.openapi_types = {
            'whichround': int
        }

        self.attribute_map = {
            'whichround': 'whichround'
        }

        self._whichround = whichround

    @classmethod
    def from_dict(cls, dikt) -> 'StartNewRoundRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The StartNewRoundRequest of this StartNewRoundRequest.  # noqa: E501
        :rtype: StartNewRoundRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def whichround(self) -> int:
        """Gets the whichround of this StartNewRoundRequest.

        Die Nummer der neuen Runde (typischerweise vorherige + 1).  # noqa: E501

        :return: The whichround of this StartNewRoundRequest.
        :rtype: int
        """
        return self._whichround

    @whichround.setter
    def whichround(self, whichround: int):
        """Sets the whichround of this StartNewRoundRequest.

        Die Nummer der neuen Runde (typischerweise vorherige + 1).  # noqa: E501

        :param whichround: The whichround of this StartNewRoundRequest.
        :type whichround: int
        """
        if whichround is None:
            raise ValueError("Invalid value for `whichround`, must not be `None`")  # noqa: E501

        self._whichround = whichround
